// Auto-categorize ingredient inputs into fridge categories
// Categories: base, vegetable, protein, spice, altro

const INGREDIENT_DICTIONARY = {
  // ===== BASE =====
  'pasta': 'base',
  'spaghetti': 'base',
  'penne': 'base',
  'fusilli': 'base',
  'rigatoni': 'base',
  'farfalle': 'base',
  'linguine': 'base',
  'tagliatelle': 'base',
  'orecchiette': 'base',
  'maccheroni': 'base',
  'bucatini': 'base',
  'lasagna': 'base',
  'lasagne': 'base',
  'gnocchi': 'base',
  'rice': 'base',
  'riso': 'base',
  'riso basmati': 'base',
  'riso integrale': 'base',
  'riso arborio': 'base',
  'riso carnaroli': 'base',
  'bread': 'base',
  'pane': 'base',
  'pane integrale': 'base',
  'piadina': 'base',
  'tortilla': 'base',
  'wrap': 'base',
  'couscous': 'base',
  'cous cous': 'base',
  'quinoa': 'base',
  'potatoes': 'base',
  'patate': 'base',
  'patate dolci': 'base',
  'farro': 'base',
  'orzo': 'base',
  'polenta': 'base',
  'bulgur': 'base',
  'noodles': 'base',
  'crackers': 'base',
  'grissini': 'base',
  'farina': 'base',
  'flour': 'base',
  'cereali': 'base',
  'cereal': 'base',
  'avena': 'base',
  'oats': 'base',

  // ===== VEGETABLE =====
  'tomatoes': 'vegetable',
  'pomodori': 'vegetable',
  'pomodoro': 'vegetable',
  'pomodorini': 'vegetable',
  'pelati': 'vegetable',
  'passata': 'vegetable',
  'zucchini': 'vegetable',
  'zucchine': 'vegetable',
  'zucchina': 'vegetable',
  'spinach': 'vegetable',
  'spinaci': 'vegetable',
  'peppers': 'vegetable',
  'peperoni': 'vegetable',
  'peperone': 'vegetable',
  'carrots': 'vegetable',
  'carote': 'vegetable',
  'carota': 'vegetable',
  'broccoli': 'vegetable',
  'broccoletti': 'vegetable',
  'lettuce': 'vegetable',
  'lattuga': 'vegetable',
  'insalata': 'vegetable',
  'rucola': 'vegetable',
  'onions': 'vegetable',
  'cipolla': 'vegetable',
  'cipolle': 'vegetable',
  'cipollotto': 'vegetable',
  'scalogno': 'vegetable',
  'aglio': 'vegetable',
  'garlic': 'vegetable',
  'melanzane': 'vegetable',
  'melanzana': 'vegetable',
  'eggplant': 'vegetable',
  'funghi': 'vegetable',
  'mushrooms': 'vegetable',
  'champignon': 'vegetable',
  'cavolo': 'vegetable',
  'cavolfiore': 'vegetable',
  'cauliflower': 'vegetable',
  'kale': 'vegetable',
  'radicchio': 'vegetable',
  'sedano': 'vegetable',
  'celery': 'vegetable',
  'finocchio': 'vegetable',
  'fennel': 'vegetable',
  'asparagi': 'vegetable',
  'asparagus': 'vegetable',
  'piselli': 'vegetable',
  'peas': 'vegetable',
  'mais': 'vegetable',
  'corn': 'vegetable',
  'cetriolo': 'vegetable',
  'cetrioli': 'vegetable',
  'cucumber': 'vegetable',
  'avocado': 'vegetable',
  'olive': 'vegetable',
  'olives': 'vegetable',
  'carciofi': 'vegetable',
  'artichoke': 'vegetable',
  'barbabietola': 'vegetable',
  'beetroot': 'vegetable',
  'verza': 'vegetable',
  'cavolo nero': 'vegetable',
  'bietola': 'vegetable',
  'chard': 'vegetable',
  'rape': 'vegetable',
  'turnip': 'vegetable',
  'zucca': 'vegetable',
  'pumpkin': 'vegetable',

  // ===== PROTEIN =====
  'chicken': 'protein',
  'pollo': 'protein',
  'petto di pollo': 'protein',
  'coscia di pollo': 'protein',
  'beef': 'protein',
  'manzo': 'protein',
  'vitello': 'protein',
  'bistecca': 'protein',
  'macinato': 'protein',
  'carne macinata': 'protein',
  'polpette': 'protein',
  'salmon': 'protein',
  'salmone': 'protein',
  'eggs': 'protein',
  'uova': 'protein',
  'uovo': 'protein',
  'tofu': 'protein',
  'tempeh': 'protein',
  'seitan': 'protein',
  'legumes': 'protein',
  'legumi': 'protein',
  'lenticchie': 'protein',
  'lentils': 'protein',
  'ceci': 'protein',
  'chickpeas': 'protein',
  'fagioli': 'protein',
  'beans': 'protein',
  'fagioli borlotti': 'protein',
  'fagioli cannellini': 'protein',
  'fagioli neri': 'protein',
  'fave': 'protein',
  'edamame': 'protein',
  'tuna': 'protein',
  'tonno': 'protein',
  'tonno in scatola': 'protein',
  'tonno sott\'olio': 'protein',
  'cheese': 'protein',
  'formaggio': 'protein',
  'mozzarella': 'protein',
  'parmigiano': 'protein',
  'grana': 'protein',
  'pecorino': 'protein',
  'ricotta': 'protein',
  'scamorza': 'protein',
  'provola': 'protein',
  'gorgonzola': 'protein',
  'fontina': 'protein',
  'stracchino': 'protein',
  'crescenza': 'protein',
  'feta': 'protein',
  'burrata': 'protein',
  'mascarpone': 'protein',
  'prosciutto': 'protein',
  'prosciutto cotto': 'protein',
  'prosciutto crudo': 'protein',
  'pancetta': 'protein',
  'speck': 'protein',
  'bresaola': 'protein',
  'salame': 'protein',
  'wurstel': 'protein',
  'salsiccia': 'protein',
  'sausage': 'protein',
  'ham': 'protein',
  'gamberi': 'protein',
  'gamberetti': 'protein',
  'shrimp': 'protein',
  'merluzzo': 'protein',
  'cod': 'protein',
  'sgombro': 'protein',
  'mackerel': 'protein',
  'acciughe': 'protein',
  'anchovies': 'protein',
  'calamari': 'protein',
  'squid': 'protein',
  'yogurt': 'protein',
  'greek yogurt': 'protein',
  'yogurt greco': 'protein',
  'latte': 'protein',
  'milk': 'protein',
  'panna': 'protein',
  'cream': 'protein',
  'burro': 'protein',
  'butter': 'protein',

  // ===== SPICE =====
  'basil': 'spice',
  'basilico': 'spice',
  'parsley': 'spice',
  'prezzemolo': 'spice',
  'rosemary': 'spice',
  'rosmarino': 'spice',
  'oregano': 'spice',
  'origano': 'spice',
  'cumin': 'spice',
  'cumino': 'spice',
  'paprika': 'spice',
  'chili': 'spice',
  'peperoncino': 'spice',
  'ginger': 'spice',
  'zenzero': 'spice',
  'curry': 'spice',
  'mint': 'spice',
  'menta': 'spice',
  'thyme': 'spice',
  'timo': 'spice',
  'soy_sauce': 'spice',
  'soy sauce': 'spice',
  'salsa di soia': 'spice',
  'lemon': 'spice',
  'limone': 'spice',
  'sesame_oil': 'spice',
  'sesame oil': 'spice',
  'olio di sesamo': 'spice',
  'cannella': 'spice',
  'cinnamon': 'spice',
  'noce moscata': 'spice',
  'nutmeg': 'spice',
  'alloro': 'spice',
  'bay leaf': 'spice',
  'salvia': 'spice',
  'sage': 'spice',
  'erba cipollina': 'spice',
  'chives': 'spice',
  'aneto': 'spice',
  'dill': 'spice',
  'coriandolo': 'spice',
  'cilantro': 'spice',
  'curcuma': 'spice',
  'turmeric': 'spice',
  'pepe nero': 'spice',
  'black pepper': 'spice',
  'aceto': 'spice',
  'vinegar': 'spice',
  'aceto balsamico': 'spice',
  'balsamic vinegar': 'spice',
  'senape': 'spice',
  'mustard': 'spice',
  'tabasco': 'spice',
  'sriracha': 'spice',
  'pesto': 'spice',
  'concentrato di pomodoro': 'spice',
  'tomato paste': 'spice',
  'capperi': 'spice',
  'capers': 'spice',
}

/**
 * Auto-categorize a free-text ingredient input
 * 1. Exact match in dictionary
 * 2. Substring match (e.g. "tonno in scatola" contains "tonno")
 * 3. No match → 'altro'
 */
export function autoCategorize(input) {
  const normalized = input.toLowerCase().trim()
  if (!normalized) return 'altro'

  // 1. Exact match
  if (INGREDIENT_DICTIONARY[normalized]) {
    return INGREDIENT_DICTIONARY[normalized]
  }

  // 2. Substring match — try longest keys first for better precision
  const sortedKeys = Object.keys(INGREDIENT_DICTIONARY).sort((a, b) => b.length - a.length)
  for (const key of sortedKeys) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return INGREDIENT_DICTIONARY[key]
    }
  }

  // 3. No match
  return 'altro'
}
